services:
  open-webui:
    image: ${OPENWEBUI_IMAGE}
    volumes:
      - data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT_HTTP:-3002}:8080
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:?error}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-True}
      - DEFAULT_USER_ROLE=${DEFAULT_USER_ROLE:-user}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - AUTHENTIK_SHARED_SECRET=${AUTHENTIK_SHARED_SECRET:-}
      - ENABLE_OLLAMA_API=${ENABLE_OLLAMA_API:-False}
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS:-true}
      - DO_NOT_TRACK=${DO_NOT_TRACK:-true}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  data: {}
