name: onyx-cwong

services:
  api_server:
    # command: sleep inf
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./download_and_extract.py:/app/download_and_extract.py
      - ./custom_cert_oauth.py:/app/onyx/httpx/custom_cert_oauth.py
      - ./onyx_backend_main.py:/app/onyx/main.py
      - /mnt/DanswerFiles/dev/tiktoken_cache:/root/.cache/tiktoken

  background:
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - ./download_and_extract.py:/app/download_and_extract.py
      - ./custom_cert_oauth.py:/app/onyx/httpx/custom_cert_oauth.py
      - ./onyx_backend_main.py:/app/onyx/main.py
      - /mnt/DanswerFiles/dev/tiktoken_cache:/root/.cache/tiktoken
